import type { SwarmVersionId, VersionTheme } from './types'

export const VERSIONS: VersionTheme[] = [
  {
    id: 'repo',
    label: 'Repo Replay',
    tagline: 'GitHub city: commits become swarm steps, files are 3D cards',
    background: '#070616',
    fog: '#1a1440',
    fogNear: 55,
    fogFar: 210,
    ground: '#14102a',
    road: '#312e81',
    ambient: 0.52,
    sun: [10, 24, 8],
    sunColor: '#c4b5fd',
    sunIntensity: 1.05,
    stars: true,
    sky: false,
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
  },
  {
    id: 'neon',
    label: 'Neon City',
    tagline: 'Night drones over a cyberpunk repo',
    background: '#0a0618',
    fog: '#22143c',
    fogNear: 50,
    fogFar: 200,
    ground: '#16122c',
    road: '#3730a3',
    ambient: 0.48,
    sun: [12, 28, 8],
    sunColor: '#a78bfa',
    sunIntensity: 1.0,
    stars: true,
    sky: false,
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
  },
  {
    id: 'chip',
    label: 'Die City',
    tagline: '2.5D silicon: lanes, transistors, electrons — tilt up to fly',
    background: '#041512',
    fog: '#0d2a24',
    fogNear: 28,
    fogFar: 90,
    ground: '#0b241c',
    road: '#d4a017',
    ambient: 0.42,
    sun: [8, 30, 4],
    sunColor: '#fde68a',
    sunIntensity: 1.05,
    stars: true,
    sky: false,
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: true,
  },
  {
    id: 'daylight',
    label: 'Daylight Atlas',
    tagline: 'The lab city, aerial and bright',
    background: '#87ceeb',
    fog: '#c7e7f5',
    fogNear: 70,
    fogFar: 240,
    ground: '#86efac',
    road: '#9ca3af',
    ambient: 0.78,
    sun: [20, 32, 10],
    sunColor: '#fff7ed',
    sunIntensity: 1.2,
    stars: false,
    sky: true,
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
  },
  {
    id: 'universe',
    label: 'Code Universe',
    tagline: 'Districts float as module islands',
    background: '#071025',
    fog: '#0f1c3a',
    fogNear: 48,
    fogFar: 190,
    ground: '#0b1224',
    road: '#4338ca',
    ambient: 0.46,
    sun: [8, 18, -6],
    sunColor: '#c4b5fd',
    sunIntensity: 0.95,
    stars: true,
    sky: false,
    floatIslands: true,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
  },
  {
    id: 'gource',
    label: 'Gource Pulse',
    tagline: 'History trails, files as living nodes',
    background: '#050508',
    fog: '#121218',
    fogNear: 30,
    fogFar: 120,
    ground: '#0a0a0c',
    road: '#27272a',
    ambient: 0.4,
    sun: [0, 20, 0],
    sunColor: '#ffffff',
    sunIntensity: 0.55,
    stars: true,
    sky: false,
    floatIslands: false,
    nodeMode: true,
    hivePull: false,
    chipMode: false,
  },
  {
    id: 'hive',
    label: 'Hive Swarm',
    tagline: 'Five agents orbit a problem crystal',
    background: '#14081f',
    fog: '#2a1248',
    fogNear: 40,
    fogFar: 160,
    ground: '#1c102e',
    road: '#7c3aed',
    ambient: 0.5,
    sun: [0, 24, 0],
    sunColor: '#f0abfc',
    sunIntensity: 1.05,
    stars: true,
    sky: false,
    floatIslands: false,
    nodeMode: false,
    hivePull: true,
    chipMode: false,
    cardMode: true,
  },
]

export function getVersion(id: SwarmVersionId) {
  return VERSIONS.find((v) => v.id === id) ?? VERSIONS[0]
}
