import type { SwarmVersionId, VersionTheme } from './types'

const DAYLIGHT_LIGHT = {
  ambient: 0.92,
  sun: [18, 34, 12] as [number, number, number],
  sunColor: '#fff7ed',
  sunIntensity: 1.35,
  fogNear: 140,
  fogFar: 420,
  stars: false,
  sky: true,
}

export const VERSIONS: VersionTheme[] = [
  {
    id: 'repo',
    label: 'Repo Replay',
    tagline: 'GitHub city: commits become swarm steps, files are 3D cards',
    background: '#dbeafe',
    fog: '#e0f2fe',
    ground: '#bbf7d0',
    road: '#94a3b8',
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
    ...DAYLIGHT_LIGHT,
    sunColor: '#f5f3ff',
  },
  {
    id: 'neon',
    label: 'Neon City',
    tagline: 'Bright cyberpunk streets, still fully lit',
    background: '#ede9fe',
    fog: '#f5f3ff',
    ground: '#c4b5fd',
    road: '#a78bfa',
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
    ...DAYLIGHT_LIGHT,
    sunColor: '#fdf4ff',
  },
  {
    id: 'chip',
    label: 'Die City',
    tagline: '2.5D silicon: lanes, transistors, electrons — tilt up to fly',
    background: '#d1fae5',
    fog: '#ecfdf5',
    ground: '#6ee7b7',
    road: '#fbbf24',
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: true,
    cardMode: false,
    ...DAYLIGHT_LIGHT,
    sun: [8, 30, 4],
    sunColor: '#fffbeb',
  },
  {
    id: 'daylight',
    label: 'Daylight Atlas',
    tagline: 'The lab city, aerial and bright',
    background: '#87ceeb',
    fog: '#dbeafe',
    ground: '#86efac',
    road: '#9ca3af',
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
    ...DAYLIGHT_LIGHT,
  },
  {
    id: 'universe',
    label: 'Code Universe',
    tagline: 'Districts float as module islands',
    background: '#e0e7ff',
    fog: '#eef2ff',
    ground: '#c7d2fe',
    road: '#818cf8',
    floatIslands: true,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
    ...DAYLIGHT_LIGHT,
    stars: true,
    sunColor: '#eef2ff',
  },
  {
    id: 'gource',
    label: 'Gource Pulse',
    tagline: 'History trails, files as living nodes',
    background: '#f1f5f9',
    fog: '#f8fafc',
    ground: '#e2e8f0',
    road: '#cbd5e1',
    floatIslands: false,
    nodeMode: true,
    hivePull: false,
    chipMode: false,
    cardMode: false,
    ...DAYLIGHT_LIGHT,
    sun: [0, 24, 0],
    sunColor: '#ffffff',
  },
  {
    id: 'hive',
    label: 'Hive Swarm',
    tagline: 'Five agents orbit a problem crystal',
    background: '#fae8ff',
    fog: '#fdf4ff',
    ground: '#f5d0fe',
    road: '#e879f9',
    floatIslands: false,
    nodeMode: false,
    hivePull: true,
    chipMode: false,
    cardMode: true,
    ...DAYLIGHT_LIGHT,
    sun: [0, 28, 0],
    sunColor: '#fff1f2',
  },
]

export function getVersion(id: SwarmVersionId) {
  return VERSIONS.find((v) => v.id === id) ?? VERSIONS[0]
}
