import type { SwarmVersionId, VersionTheme } from './types'

/** Shared Daylight Atlas look: bright sky, no night palette. Fog fields unused (scene has no fog). */
const ATLAS = {
  background: '#87ceeb',
  fog: '#87ceeb',
  fogNear: 1e6,
  fogFar: 1e6,
  ground: '#86efac',
  road: '#9ca3af',
  ambient: 0.95,
  sun: [20, 32, 10] as [number, number, number],
  sunColor: '#fff7ed',
  sunIntensity: 1.4,
  stars: false,
  sky: true,
}

export const VERSIONS: VersionTheme[] = [
  {
    id: 'board',
    label: 'Code Board',
    tagline: 'Chessboard tiles on the floor — inspect flips them up to read',
    ...ATLAS,
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
  },
  {
    id: 'repo',
    label: 'Repo Replay',
    tagline: 'GitHub city in daylight: commits become swarm steps',
    ...ATLAS,
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
  },
  {
    id: 'neon',
    label: 'Neon City',
    tagline: 'Daylight streets with color accents, fully lit',
    ...ATLAS,
    road: '#818cf8',
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
  },
  {
    id: 'chip',
    label: 'Die City',
    tagline: '2.5D silicon in daylight — tilt up to fly',
    ...ATLAS,
    sun: [8, 30, 4],
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: true,
    cardMode: false,
  },
  {
    id: 'daylight',
    label: 'Daylight Atlas',
    tagline: 'The lab city, aerial and bright',
    ...ATLAS,
    floatIslands: false,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
  },
  {
    id: 'universe',
    label: 'Code Universe',
    tagline: 'Districts float as module islands under a clear sky',
    ...ATLAS,
    floatIslands: true,
    nodeMode: false,
    hivePull: false,
    chipMode: false,
    cardMode: true,
  },
  {
    id: 'gource',
    label: 'Gource Pulse',
    tagline: 'History trails, files as living nodes in daylight',
    ...ATLAS,
    sun: [0, 28, 0],
    sunColor: '#ffffff',
    floatIslands: false,
    nodeMode: true,
    hivePull: false,
    chipMode: false,
    cardMode: false,
  },
  {
    id: 'hive',
    label: 'Hive Swarm',
    tagline: 'Five agents orbit a problem crystal in daylight',
    ...ATLAS,
    road: '#e879f9',
    sun: [0, 28, 0],
    floatIslands: false,
    nodeMode: false,
    hivePull: true,
    chipMode: false,
    cardMode: true,
  },
]

export function getVersion(id: SwarmVersionId) {
  return VERSIONS.find((v) => v.id === id) ?? VERSIONS[0]
}
